spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz@WSX
    url: jdbc:mysql://106.12.88.80/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 106.12.88.80
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wxbcbfb086efef5f09
  mpAppSecret: b560b1b193b32d61f7baa0aa2eece1d1
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl: http://istimeless.natapp1.cc/sell/pay/notify
  weChatMpAuthorize: http://istimeless.natapp1.cc
  weChatOpenAuthorize: http://istimeless.natapp1.cc
project:
  sell: http://istimeless.natapp1.cc
  